main.go
I've gone with 1 for now, but I might make it more specific in the future.
Closes #16
=> fix: set exit code to 1 if there are vulnerabilities

main.go
Currently, this is happening _after_ we load the database which is technically not required for
parsing, but I think it makes sense to load the database first on the main flow so have left it as
is for now.
We should improve on this in the future - I'm hoping we can load the database in parallel to
parsing, but even just having a "don't need to load" check would be fine.
Documentation will be in a follow-up PR, because I'm also documenting `--list-ecosystems`.
=> feat: support `--list-packages` command flag

CONTRIBUTING.md, detector/parsers/parse-composer-lock.go, detector/parsers/parse-npm-lock.go, detector/parsers/parse-yarn-lock.go
I realised that all the `prealloc` errors were actually valid, and that what I had in #27 is actually fine as `len` cannot return a negative it's just that Go currently cannot express that.
I _think_ that makes it completely safe (as the worse case should be that we overflow resulting in a smaller-than-required allocation which shouldn't result in the tool actually crashing)...
=> pref: pre allocate some arrays

.goreleaser.yml
I'd meant to change this originally but then forgot 😅 
I think it's a better experience to provide binaries as-is as it should make it slightly easier to download in scripts and CIs.
=> ci: output binaries instead of zips

detector/database/osv.go, main.go
I'm not the happiest about this as it adds a lot to the output in terms of wrapping given the potential size of the summaries, but there is still a lot of thinking to be done about the output formats, and I think having the advisory link is very important so for now it's worth it.
=> feat: include advisory link in output

detector/database/cache.go
I'm pretty sure this doesn't actually help in the way the linter wants, but it was this or disabling it (inline) 🤷 
I get what it's wanting, but for now am not concerned since the rest of the tool isn't using it, and I'm currently not expecting people to be using this directly as a Go package (not that they couldn't if they want, just I'm focusing on the compiled tool for now)
Fixes #26
=> refactor: use `NewRequestWithContext` with background context

detector/parsers/parsers_test.go
~Ideally it would be good to dynamically grab the list or something, but this'll do for now 🤷~
Have a "dynamic" count based on non-test files prefixed with `parse-` which should be pretty good.
=> test: write a case for `TryParse`

.goreleaser.yml
=> build: set the `date` variable to be the date of the latest commit

.golangci.yaml, detector/parsers/fixtures/pip/with-added-support.txt, detector/parsers/parse-requirements-txt.go, detector/parsers/parse-requirements-txt_test.go
I'm pretty sure that technically the advisories are actually wrong as e.g. `twisted[http2]` is technically a different package to `twisted` itself but I can understand that it'd make the number of advisories to maintain grow by a large factor.
At this point I think it's less likely that an advisory will be missed with this change than without it, but if we find later one is being missed, we'll deal with it somehow 🤷
=> fix: support python packages that have "added support" syntax

detector/database/osv.go, detector/database/osv_test.go, detector/parsers/fixtures/pip/non-normalized-names.txt, detector/parsers/parse-requirements-txt.go, detector/parsers/parse-requirements-txt_test.go
The comments should say it all - ultimately I realised that `pip-compile` is probably why all the `requirements.txt` I have locally are using lowercase package names, and that pip probably just accepts either or and normailizes names internally.
Ultimately the OSV spec says that the name for packages in the PyPip ecosystem should be normalized, so let's normalize the names on both sides and call it a day for the time being.
=> fix: normalize names of python packages to favor false positives over false negatives

detector/database/osv.go, detector/database/osv_test.go
This is needed for #53 as it uses `SEMVER` for some ecosystems like `npm`.
While we could use the native `semver`, frankly our custom `semver` should be able to handle this and I actually wasn't able to get the native `semver` working 😂
=> feat: support SEMVER ranges

detector/database/osv.go, detector/database/osv_test.go
Needed for #53, as some advisories only have `versions` (typically for those with single exact versions that are vulnerable)
=> feat: support OSV advisories with just `versions` array in affected

README.md, detector/database/cache.go, detector/database/load.go, detector/database/new.go, detector/parsers/parsers.go, main.go
This is working, but there's a few tweaks still to be made, and will also have some follow ups.
Resolves #53
=> feat: use osv.dev databases instead of github advisory database

detector/database/osv.go, detector/database/osv_test.go, main.go
The output format is slowly getting better 😄 
Currently I'm applying truncation to just the "details" text as the summaries seem short enough and really this is meant to be a fallback now that we're using more than just the GH advisory database.
I have just realised a slight improvement for linking would be to check if the `aliases` contain any GHSA IDs - will do that in a follow-up PR.
=> fix: improve description of OSVs to handle summary not being present + linking to non GH advisories

detector/database/osv.go, detector/database/vulnerabilities.go, detector/database/vulnerabilities_test.go
Not super happy about this one as it feels really inefficient to be constantly doing the same bunch of loops over and over, but I can't think of a more efficient way of doing this - the main issue is that not everyone lists all their aliases, so we just have to check them from every angle...
This messed with my brain a bunch, so I've made `Include` public for now to be able to have a explicit test but will replace that once I've had time to look into writing tests for the database (which require running a test http server to provide the db archive).
Overall this is primarily "just" for the PyPip ecosystem as their database has both GHSA and PYSEC vulnerabilities, with the GHSA ones having been pulled from PYSEC in the first place; however what they are doing is completely valid so we …
=> fix: don't report vulnerabilities multiple times under different aliases

internal/lockfile/parse.go, internal/lockfile/parse_test.go, main.go
It's a little more accurate, as the "try" part is represented by it returning `error`.
=> refactor: rename `lockfile.TryParse` to `lockfile.Parse`

README.md, internal/lockfile/ecosystems.go, internal/lockfile/ecosystems_test.go, main.go
This is useful on it's own, and also ends up giving `--list-ecosystems` a use since it'll be able to just call `KnownEcosystems`.
Will do some deduplication with `numberOfLockfileParsers` in a followup.
=> feat: add `--cache-all-databases` flag

README.md, main.go
It's not that useful since we list the ecosystems in the readme, but it was this or remove it and it might become more useful later 🤷
=> fix: make `list-ecosystems` flag actually useful again

internal/lockfile/parse.go
This ensures that the output is consistent over multiple audit runs, which makes it easier to compare.
=> fix: sort packages with the same name by their versions

README.md, main.go
This also tweaks the output a bit - I'm not strictly super super happy with it, but it should be fine 🤷 (I think the colors might be overkill, and the indenting, but will play around with some stuff later)
Technically we could optimise the database loading to avoid re-loading databases for ecosystems we're already loaded in previous loops, but currently it doesn't impact speed to be worth the complexity.
I also realised if we had a flag like `--ignore-unknown-files`, this would allow you to do `osv-detector */**` and co 🤔 
Resolves #12
=> feat: support being passed multiple files

internal/semantic/compare_test.go, internal/semantic/parse.go, internal/semantic/parse_test.go, internal/semantic/version.go
All versions in the OSV advisories are strictly semver, so have no leading "v" - however `composer` packages can have an optional leading v, which currently causes the whole version string to be treated as having no components and just a build string.
This changes that to trim out the leading "v" if present - I've implemented this to actually track if the version had a leading "v" and undo the trim + track if the string turns out to have no components, because it was straightforward to do and so a nice optional extra.
=> fix: trim off leading "v" in version strings when parsing

.golangci.yaml, internal/database/ecosystems.go, internal/database/osv.go
Now that we're got a reporter, ideally all output should be done through that to ensure we're always outputting valid JSON to `stdout` when that mode is enabled.
Ironically, we can enable the `forbidigo` linter to help enforce this.
=> fix: remove unneeded debug logs

main.go
Not really surprised a bug like this slipped through 🤷
=> fix: prepend directory path when finding lockfiles in a directory

main.go
We exit with code `1` when there is at least one affected vulnerability, which isn't the case for this situation so we should instead exit with code `127`.
=> fix: exit with "generic error" code instead of "vuls. found" code when no valid path is provided

main.go
This beings it inline with the other `printX` functions, and while saved a couple of code lines it was actually giving the function two responsibilities - it's cleaner to have it only handle the printing.
=> refactor: separate exit code value from `printDatabaseLoadErr`

internal/lockfile/parse.go, internal/lockfile/parse_test.go, main.go
Currently if you do `osv-detector --parse-as my-file path/to/directory`, we error with "You must provide at least one path to ..." because we've failed to find at least one file that we can parse.
This doesn't make sense because the user has attempted to provide a path to a directory containing at least one lockfile, and really the issue is that they've told us to parse the files as something we don't support parsing.
This resolves that by having us check if we do actually support parsing files in the format the user has specified, before attempting to identify which files we should actually be checking. It also felt a bit mean to not provide the user with an explicit list of valid inputs for `--parse-as` so I switched to using a map instead of a switch (which is a bit better all around …
=> fix: validate `--parse-as` to ensure error output in case a directory is passed

README.md, internal/lockfile/ecosystems.go, internal/lockfile/fixtures/maven/empty.xml, internal/lockfile/fixtures/maven/interpolation.xml, internal/lockfile/fixtures/maven/not-pom.txt, internal/lockfile/fixtures/maven/one-package.xml, internal/lockfile/fixtures/maven/two-packages.xml, internal/lockfile/parse-maven-lock.go, internal/lockfile/parse-maven-lock_test.go, internal/lockfile/parse.go, internal/lockfile/parse_test.go
While I've done a bit of Java (mainly from my uni days), I've never done a lot with the ecosystem so didn't know much about how dependencies were actually managed other than them coming from Maven, and so I didn't really realise that Java / Maven doesn't actually have a lockfile.
This results in the all the standard caveats of not having a lockfile: there's no way of knowing the actual exact versions of libraries being used, so it's not possible to give a completely accurate report on what known vulnerabilities impact a project.
This doesn't mean this parser is useless, just that it's going to be the worst for "casual use" (e.g. "just scan my project") as for best results developers are going to have to craft a detailed `pom.xml` that specifies all their dependencies in as exact versions …
=> feat: support parsing pom.xml / maven / java

.github/workflows/checks.yml, .github/workflows/release.yml
CI is failing because we're using the latest version of `golangci-lint` which has some changes - I fully plan to upgrade, but we should be pinning our version in CI anyway to at least match what's in our `Makefile`, so this does that.
I also noticed a few actions were out of date, so have upgraded them.
=> ci: pin `golangci-lint` version & upgrade actions

README.md, internal/database/vulnerabilities.go, internal/database/vulnerabilities_test.go, internal/reporter/report.go, internal/reporter/report_test.go, main.go
This adds support for being able to ignore vulnerabilities so that `osv-detector` does not exit with a non-zero exit code if the ignored vulnerabilities are the only ones present.
Ignores are applied to all packages being checked which should be enough as OSVs only apply to one package from what I've seen (though they can apply to the same package across different ecosystems, but that should be fine).
We _don't_ check if the ignores provided map to known vulnerabilities nor that all of the vulnerabilities that are expected to be ignored are present - while I'd like to, I think it'd be very tricky because you'd need to check that the ignored vulnerability isn't in _any_ of the packages specified in _all_ of the lockfiles (this is compounded if you add config files into the mix, because …
=> feat: support ignoring vulnerabilities

internal/lockfile/parse_test.go
I was having a quick look over the test coverage and saw this wasn't covered.
=> test: add cases for `lockfile.Ecosystems` function

.prettierignore, README.md, internal/configer/fixtures/ext-yaml-invalid/.osv-detector.yaml, internal/configer/fixtures/ext-yaml/.osv-detector.yaml, internal/configer/fixtures/ext-yml-invalid/.osv-detector.yml, internal/configer/fixtures/ext-yml/.osv-detector.yml, internal/configer/fixtures/invalid/.osv-detector.yml, internal/configer/load.go, internal/configer/load_test.go, main.go
This adds support for config files, which can be used for specifying ignores in a way that can be tracked e.g. in version control.
Right now the only valid config option is `ignore` which takes an array of OSV ids to be ignored (matching the `--ignore` flag), since that's the flag we have that makes sense to configure per-project, but I think this could be useful in future for supporting custom databases.
Config is merged with any flags, meaning if you specify ignores in both the config & as flags they'll all be taken (rather than just the ignores from flags or the config). You can use `--no-config` to tell the detector to not load any config files.
The config must be in YAML format, and the default config file is `.osv-detector.yaml` & `.osv-detector.yml`.
=> feat: support config file

.github/workflows/release.yml
Releases have been failing for an unknown reason:
```
⨯ release failed after 170.51s error=scm releases: failed to publish artifacts: PATCH https://api.github.com/repos/G-Rath/osv-detector/releases/0: 404 Not Found []
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.9.0/x64/goreleaser' failed with exit code 1
```
* https://github.com/G-Rath/osv-detector/runs/6513401634?check_suite_focus=true
* https://github.com/G-Rath/osv-detector/runs/6513046522?check_suite_focus=true
* https://github.com/G-Rath/osv-detector/runs/6513271249?check_suite_focus=true
I can't find anything on the `goreleaser` GitHub and I've not changed anything about my GitHub but the last successful release was done using `goreleaser` v1.8.3 whereas now we're using (and failing on) v1.9.0 so going to see if the …
=> ci: pin `goreleaser` to specific version

.github/workflows/release.yml
https://github.com/goreleaser/goreleaser/issues/3115 should be resolved in v1.9.1 so we should be fine to use latest again.
=> ci: use latest version of `go-releaser` again

main.go
I sort of did this when toying with a possible improvement with #94, and it is technically an improvement because it means we're only loading each database once instead of per lockfile
The real improvement (and reason for landing this) imo is that now the database loading details are outputted first:
```
❯ osv-detector-t .
Loading OSV databases for the following ecosystems:
npm (2427 vulnerabilities, including withdrawn - last updated Fri, 10 Jun 2022 00:28:07 GMT)
PyPI (3172 vulnerabilities, including withdrawn - last updated Fri, 10 Jun 2022 00:46:34 GMT)
package-lock.json: found 1183 packages
ansi-regex@3.0.0 is affected by the following vulnerabilities:
GHSA-93q8-gq69-wqmw:  Inefficient Regular Expression Complexity in chalk/ansi-regex …
```
=> feat: parse all lockfiles and load all databases before checking for vulnerabilities

internal/reporter/report_test.go, internal/reporter/reporter.go, internal/reporter/reporter_test.go, main.go
These arguably make sense to belong to `reporter`, and this means we can test them + reduce the size of `main.go` a little.
Have also snuck a test in to get us to 100% coverage of the `reporter` package 🎉
=> refactor: move reporter functions into `reporter` package

pkg/lockfile/fixtures/pnpm/tarball.yaml, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pnpm-lock_test.go
When researching how `pnpm` represents git dependencies in it's lock to support extracting commits, I found out a bit more on how the dependencies paths work.
Turns out `pnpm` captures the `name` and `version` within the dependency path if possible, otherwise it includes them as a property - so if either of those properties are present we should favor them over whatever we extract from the dependency path.
This has also highlighted that this parser is probably the most inaccurate, but I'm not too fussed because it should only be falling over on exotic cases and I've not got a lot of easy reference to confirm what is and isn't correct so for now I'll have to rely on people opening issues if they find something is not being parsed correctly.
=> fix: use `name` and `version` properties if present when parsing `pnpm.yaml` locks

README.md, pkg/lockfile/fixtures/bundler/has-git-gem.lock, pkg/lockfile/parse-gemfile-lock.go, pkg/lockfile/parse-gemfile-lock_test.go
=> feat: support parsing commits from `Gemfile.lock` files

README.md, internal/types.go, pkg/lockfile/csv.go, pkg/lockfile/csv_test.go, pkg/lockfile/fixtures/csv/commits.csv, pkg/lockfile/parse.go
I'm not the happiest about effectively making an empty ecosystem valid, but the alternative was to have a special ecosystem which had other annoying qualities.
I've set `ecosystem` to be omitted if it's empty when outputting as JSON, though I'd prefer `null` but I got a panic when I tried a custom marshaller and honestly it should be fine 🤷 
Resolves #110
=> feat: support commits in csv

pkg/lockfile/parse.go, pkg/lockfile/parse_test.go
This makes sense once #111 is landed. I've also included a few test cases that weren't previously being covered (getting us a total 0.5% more coverage!)
=> fix: represent empty ecosystems with `"<unknown>"`

internal/reporter/report.go, internal/reporter/report_test.go, internal/reporter/reporter.go, internal/reporter/reporter_test.go, pkg/lockfile/parse.go, pkg/lockfile/parse_test.go, pkg/semantic/compare_test.go, pkg/semantic/parse_test.go, pkg/semantic/version.go
At the time I didn't know that Go already has a `ToString` convention, which is `String`.
While renaming doesn't let us remove any code (or maybe it does, I've just not hunted around for it), this should increase operability for those using the packages.
=> refactor: rename `ToString` functions to `String`, per go convention

pkg/database/zip.go, pkg/database/zip_test.go
Currently when running in offline mode the detector outputs "last updated )":
```
❯ osv-detector-t --offline --parse-as csv-row ''
Loaded the following OSV databases:
GHADB (reviewed) (0 vulnerabilities, including withdrawn - last updated )
-: found 0 packages
Using config at ./.osv-detector.yaml (1 ignore)
Using db GHADB (reviewed) (0 vulnerabilities, including withdrawn - last updated )
no known vulnerabilities found
```
This fixes that by setting `UpdatedAt` to be based off the caches date when in offline mode. I've also chunked in some more cache-focused tests (including one that catches this bug), which increases our coverage by a couple of percents.
=> fix: use updated at date from cache when in offline mode

main.go
This ensures that the order we operate (and thus output details about) lockfiles is deterministic regardless of OS and filesystem
Cherry picked from #118
=> fix: make lockfile order deterministic

.github/workflows/checks.yml, .github/workflows/release.yml
This landed last month, let's us make our CI workflow a little smaller.
=> ci: use built-in cache setting for `actions/setup-go`

.github/workflows/release.yml
I realised while doing #122 I forgot to update the version of Go being used in the release workflow 😬
=> ci: update version of Go used for releases

.github/workflows/codeql-analysis.yml
I noticed this while reporting https://github.com/actions/setup-go/issues/240 - there's actually two warnings:
```
Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
Warning: 1 issue was detected with this workflow: Please make sure that every branch in on.pull_request is also in on.push so that Code Scanning can compare pull requests against the state of the base branch.
```
I think the second warning is a bug that should hopefully be fixed by this upgrade, but will double check after this is merged.
=> ci: upgrade codeql actions to v2

.github/workflows/checks.yml, .github/workflows/release.yml
Currently we get a bunch of "errors":
Turns out this action already does the caching, and these errors come out as annotations which means any issues won't be nicely highlighted since there's a very low limit on how many annotations each job can output.
=> ci: don't use `actions/setup-go` cache for golangci-lint as it has its own cache

pkg/lockfile/parse-yarn-lock-v1_test.go, pkg/lockfile/parse-yarn-lock-v2_test.go
A mistake from the early days 😅
=> test: adjust yarn lock parser case names to match parser function name

fixtures/csvs-files/not-a-csv.xml, fixtures/csvs-files/two-rows.csv, main_test.go
Originally I was doing some easy pickings (including some that result in more coverage in #114 vs right now), and now I've found a few bugs in the `csv-row` parser 🤦 (I'll address them in follow up PRs)
=> test: add more coverage of cli core

main.go, main_test.go
This is the initial big bug I found when doing #128, since right now `csv-row` is completely broken - I've also found a panic while aiming for complete coverage, which I'll address in a follow up PR.
=> fix: pass args to parser when using `--parse-as csv-row`

main_test.go, pkg/lockfile/csv.go, pkg/lockfile/csv_test.go
Currently we panic if you don't provide the third field (version/commit), even though we do support it being blank - for now I've gone with just always requiring three fields since it just means adding a trailing comma.
=> fix: require at least three fields to be present in csv row

main.go, main_test.go
Very minor but I realised while building some tooling to use `osv-detector` that our error message for this situation could be better...
=> fix: adjust error message to indicate directories must have "at least one" lockfile

README.md, main.go, main_test.go
These flags are useful for automated tooling and those paranoid about downloading arbitrary zip files from untrusted sources. I'm still not labeling this a security issue because there has to be another step to allow getting the config file to the detector in the first place which either means you trust the source enough to explicitly pull in its config (e.g. with a `git clone`) or you've already been compromised (in which case its a moot point).
Resolves #136
Resolves #133
=> feat: support skipping specific parts of configs

pkg/database/osv.go, pkg/database/osv_test.go
See https://github.com/ossf/osv-schema/issues/35
I think I've implemented this correctly but it's a little hard to tell for sure until someone actually creates OSVs with it 😅 
Resolves #140
=> feat: support `last_affected` in OSVs

README.md
I've got `osv-detector-t` aliased in my shell to point to the current local dev build, and I've been trying so hard to make sure it never got committed into the repo since all my work is using that; apparently I have failed 😭
=> docs: use correct command in jq pipe example

main.go, main_test.go
This makes it easier for tools to know when the detector didn't find anything to parse vs anything else - this is an important situation because this way tools can just point the detector at a directory without knowing if there will be anything for the detector to be able to parse.
=> feat: use a unique exit code to indicate that no lockfiles could be found in the given args

README.md, main_test.go, pkg/lockfile/parse.go, pkg/lockfile/parse_test.go
`cargo` lockfiles starts with a capital letter: https://doc.rust-lang.org/cargo/appendix/glossary.html
The current parsers map has `cargo.lock`, which means it fails to find a parser when pointed to a standard cargo lock file, this PR just replaces all instances of `cargo.lock` with `Cargo.lock`. All tests still seem to pass.
=> Update parsers map to correct cargo.lock to Cargo.lock

pkg/semantic/compare.go, pkg/semantic/compare_test.go, pkg/semantic/parse.go, pkg/semantic/parse_test.go, pkg/semantic/version.go
I realised this when working on an overhaul of `semantic` that switches it to use ecosystem-specific comparators for better accuracy.
While I'm almost done with that work, landing this first would make the diff a little smaller and this is technically a bug anyway.
@another-rex I'm pretty sure this won't impact you because you're currently just using `lockfiles` but heads up all the same just in case :)
=> fix: switch to using `big.Int` in version parsing & comparing to support really large numbers

.golangci.yaml, main.go, pkg/database/mem-check.go, pkg/semantic/parse_test.go
I didn't realise that this wasn't actually being checked by CI/linting 😬
=> chore: enable `gofmt` formatter

.golangci.yaml, internal/configer/load_test.go, main_test.go, pkg/database/api-check.go, pkg/database/api-check_test.go, pkg/database/api-fetch.go, pkg/database/config.go, pkg/database/zip.go, pkg/database/zip_test.go, pkg/lockfile/ecosystems_test.go, pkg/lockfile/parse-cargo-lock.go, pkg/lockfile/parse-composer-lock.go, pkg/lockfile/parse-gemfile-lock.go, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-npm-lock.go, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse.go, pkg/lockfile/parse_test.go
This is effectively a "backport" of changes that will be required when upgrading `golangci-lint` to v1.49.0 - I've not upgraded to it yet because it requires Go 1.19 and that adds an extra ~200kb to our binary size which I don't feel like taking on just yet.
This also disables `ireturn` because it's not bring me joy; that was cherry-picked from #157.
=> refactor: move off deprecated `io/ioutil` methods, use `http` method constants, and adjust lint comments

pkg/lockfile/fixtures/go/replace-different.mod, pkg/lockfile/fixtures/go/replace-local.mod, pkg/lockfile/fixtures/go/replace-mixed.mod, pkg/lockfile/fixtures/go/replace-no-version.mod, pkg/lockfile/fixtures/go/replace-not-required.mod, pkg/lockfile/fixtures/go/replace-one.mod, pkg/lockfile/parse-go-lock.go, pkg/lockfile/parse-go-lock_test.go
In theory this adds support for `replace`, though in practice it's only going to be useful when the replacement package is remote because there's no way to resolve the local package to the corresponding remote package name that'll be in OSVs - it's tempting to try and infer that from the target (e.g. if you're replacing `golang.org/x/net` with `./fork/net`, then it could be reasonable to assume its a fork of `golang.org/x/net`) but in practice there's no way to know when that shouldn't be applied either.
Likewise for the version, if there isn't one set as part of the replacement then there's not really anything that can be done because there's no requirement from Go that a version be specified for the replacement package anywhere on disk - the best that could be done would be to try and …
=> fix: handle `replace` directives in `go.mod` files

pkg/semantic/parse_test.go
Gets us a bit of extra coverage
=> test: add cases for `semantic.MustParse`

pkg/lockfile/fixtures/pnpm/files.yaml, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pnpm-lock_test.go
Turns out `..` is a thing, but then actually we shouldn't be doing any dependency path parsing for `file:` dependencies
=> fix: avoid panic when parsing `file:` dependencies in `pnpm` lockfiles

pkg/lockfile/parse-cargo-lock_test.go, pkg/lockfile/parse-gemfile-lock_test.go, pkg/lockfile/parse-poetry-lock_test.go
`Gemfile.lock` is nothing close to JSON, so this test doesn't make sense - removing it does not decrease coverage either, so lets axe it.
My best guess is that it came from copying the standard set of tests from one of the other parsers, and then not realising it since it never failed 🤷
I also noticed two test cases were incorrectly named "json" instead of "toml", so have corrected that too
=> test: remove nonsense case and correct names (#187)

.github/workflows/semantic.yml
Most of this should be understandable from reading the workflow itself, but a general overview is that this workflow runs each `semantic` fixture generator, collecting their generated fixture file as an artifact (`generated-versions.zip`, which is appended to by each job), and then that artifact is used in a run of the whole test suite to ensure `semantic` passes (which happens regardless of if any of the generators failed or not)
A bonus byproduct of this is that the artifact can be downloaded so that the contents can be easily committed on occasion without needing to have all the different languages setup locally; I've also configured the workflow to run every Sunday, whenever a generator is changed in a PR (as an easy way to double check that they work after the change), and via …
=> ci: setup workflow for running `semantic` fixture generators regularly

pkg/semantic/version-maven.go
It turns out that the fix I did in #179 while technically correct,  was only required because of another bug which is that I'm using the wrong variable 😅
=> fix: trim leading zeros off when comparing numerical components in Maven versions (properly)

README.md, main.go, main_test.go
This is effectively abusing a string to represent what is actually a tuple, and does mean we're doing a little extra work sometimes because we parse at least twice, but overall it works pretty nice imo so I think for now at least it's fine as doing something like a tuple would make it more complex 🤷
=> feat: support providing `parse-as` per lockfile / directory

pkg/lockfile/fixtures/pip/line-continuation.txt, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
Originally implemented by @robotdana - have updated for Go v1.17
=> fix: handle line continuations in `requirements.txt` files

pkg/lockfile/fixtures/pip/with-hash.txt, pkg/lockfile/fixtures/pip/with-per-requirement-options.txt, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-requirements-txt_test.go
Originally implemented by @robotdana - have updated for Go v1.17
Branched off #195
=> fix: support requirements with options in `requirements.txt`

pkg/database/osv.go, pkg/database/osv_test.go
While the spec recommends that `affected` entries be sorted in order, it's not required and the comparison algorithm explicitly sorts `affected` before comparing.
I'd originally not done this because the databases generally being consumed by the detector do follow the recommendation and I didn't want the extra complexity but now that we have `semantic` this is very easy
=> fix: ensure that affected entries are in order before comparing

go.mod, go.sum, main_test.go, pkg/database/dir_test.go, pkg/database/zip_test.go
This should make it a bit easier to maintain the fixtures, though it does include false positives since it can't handle the `%%` replacements but that should be easy to understand.
=> test: use diff module

pkg/lockfile/parse-pnpm-lock.go
I realised first that `strings.Contains` could be used instead of `strings.Index` but then realised we can just always do the `strings.Split` (which'll later get replaced with a `strings.Cut` after go 1.19) 🤷
=> refactor: remove unneeded index check in favor of just always splitting

internal/cachedregexp/regex.go, main_test.go, pkg/database/osv.go, pkg/lockfile/parse-gemfile-lock.go, pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-mix-lock.go, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-requirements-txt.go, pkg/lockfile/parse-yarn-lock.go, pkg/semantic/version-maven.go, pkg/semantic/version-packagist.go, pkg/semantic/version-pypi.go, pkg/semantic/version-semver-like.go
This should only really be noticable when using the detector against a lot of the same kind of files which is more likely if its being used as a library, but this is still a nice optimization since the worse-case should be "same speed"
=> perf: cache regexp compiles

.github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/semantic.yml
Most notably `actions/setup-go` solved the slow Windows file cache in v4, so that should be noticeably faster 🎉
=> ci: update actions

.github/workflows/semantic.yml
I had opened the fixtures might have stabilized over time, but they have not - I'll be considering what to do long term, but for now this is an easy way to ensure the weekly `semantic` tests don't constantly fall over.
=> ci: regenerate e2e fixtures when running scheduled semantic tests

.github/workflows/checks.yml, .github/workflows/semantic.yml, main_test.go
They're just too noisy and don't add any extra code coverage
=> test: disable e2e tests by default

.github/workflows/semantic.yml
=> ci: don't download non-existent e2e artifact

generators/GenerateMavenVersions.java, generators/generate-cran-versions.R, generators/generate-debian-versions.py, generators/generate-packagist-versions.php, generators/generate-pypi-versions.py, generators/generate-rubygems-versions.rb
Currently the generators assume that all packages in an OSV are for their respective ecosystem which since they download ecosystem-specific databases is _mostly_ true, but there are a few OSVs that are for packages that exist across more than one ecosystem.
This has not been a problem up until now because either the versions in such OSVs happen to be compatible with native ecosystem version parser or we're skipping invalid versions for legacy reasons, but now GHSA-5844-q3fc-56rh exists which has versions that are invalid in Ruby.
=> chore: only extract versions from packages in the generator ecosystem

internal/configer/load.go, internal/reporter/reporter.go, internal/reporter/reporter_test.go, main.go
When I originally implemented `Reporter`, IDEs such as GoLand didn't support custom `Printf` functions so I stuck with plain methods and did the `fmt` formatting on the string; that's changed as of GoLand 2023.3 via [GO-5841](https://youtrack.jetbrains.com/issue/GO-5841) 🎉
=> refactor: handle string formatting within the reporter

pkg/database/api-check_test.go, pkg/database/zip_test.go
I recently learned about this, which saves a few lines of code - from what I can tell there's not a huge advantage over `defer` in non-helpers, but I think the consistency is nice
=> test: use `t.Cleanup` instead of `defer`

go.mod, go.sum, internal/configer/load.go, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pubspec-lock.go
This upgrades us to use the latest v3 version of the YAML library along with updating our unmarshal functions to use the new interface.
While this annoyingly adds ~20kb to the binary, it gives us access to more stuff like information about comments and line numbers when unmarshalling and the ability to write indented output (which will be used for #248) - ultimately, we might as well just get the upgrade over with.
=> refactor: update YAML library to v3

generators/GenerateMavenVersions.java, generators/generate-cran-versions.R, generators/generate-debian-versions.py, generators/generate-packagist-versions.php, generators/generate-pypi-versions.py, generators/generate-rubygems-versions.rb
This has always been allowed by the spec but now there's at least one real-world advisory in the Debian database like this which causes it to error.
=> chore: ensure that `package` exists in `affected` property in generators

.github/workflows/checks.yml, .github/workflows/release.yml, .github/workflows/semantic.yml
This is a bit better from a security POV
=> ci: explicitly define permissions at the job level

fixtures/locks-e2e/1-pom.xml, fixtures/locks-e2e/2-pom.xml
This doesn't actually matter but it makes codeql happy
=> chore: use `https` in pom fixtures

README.md
Apparently it's case sensitive 🤷
=> docs: update scorecard badge link

.github/workflows/scorecard.yml
This was the version that the workflow generator used but we can safely upgrade to v4
=> ci: update `actions/upload-artifact` to non-beta version

.github/workflows/release.yml, .goreleaser.yml
Per https://goreleaser.com/blog/goreleaser-v2 and https://goreleaser.com/deprecations
=> ci: update `goreleaser/goreleaser-action` to v6 and `goreleaser` to v2

main_test.go
Seems like this bug has been fixed so we're now getting the expected 404 error code
=> test: update expected stderr output

.github/workflows/checks.yml, .golangci.yaml, Makefile, internal/reporter/reporter_test.go, main_test.go, pkg/database/api-check.go, pkg/database/api-check_test.go, pkg/database/zip_test.go
We can't go any higher right now because the next version required Go v1.22, and results in some errors
=> refactor: update `golangci-lint` to v1.59

.golangci.yaml, internal/reporter/reporter_test.go, main.go, pkg/semantic/version-pypi.go
While I was initially going to label this as a `perf`ormance improvement, after seeing how few lines are being changed I'm just going to call it a `refactor`
=> refactor: enable `perfsprint` to ensure performant string printing

pkg/semantic/parse.go
Having ecosystems sorted by their name makes it easier to review this section of code
=> refactor(semantic): sort ecosystems by name

pkg/semantic/version-rubygems.go
I realised that I have overly complicated the act of returning the result of comparing components in this function, and that the last two conditions will never be true as we loop over the largest number of components 😅
=> refactor(semantic): simplify comparing of RubyGem version components

pkg/semantic/version-pypi.go
Currently this return is not covered because we're explicitly doing all three possible comparisons, so we might as well move the equality check to the end as the default
=> refactor(semantic): remove unneeded condition in PyPI version comparator

pkg/semantic/version-semver-like.go
While I'm a little reluctant to do this as I'm sure I included these for a reason, they're apparently not covered by any tests and the longer they remain the more likely someone might start actually depending on them.
I'm pretty sure the bulk of this was present as part of having `semantic` rebuild the parsed version for debugging when I was writing the implementation, but that's not actually a feature so we don't explicitly need to be doing it - this won't stop us from reintroducing the logic in future if we decide we want it
=> refactor(semantic): remove unneeded logic in parsing semver-like versions

pkg/lockfile/parse-maven-lock.go, pkg/lockfile/parse-maven-lock_test.go
Turns out that actually managed dependencies should not take precedence over standard dependencies, as they're not real dependencies (at least when scanning only root `pom.xml`s)
Also see https://github.com/google/osv-scanner/pull/1000
=> fix: process managed dependencies before standard dependencies when parsing `pom.xml`s

pkg/lockfile/fixtures/pnpm/invalid-package-path.yaml, pkg/lockfile/parse-pnpm-lock.go, pkg/lockfile/parse-pnpm-lock_test.go
While this is invalid, it's better to return an error than `panic`
=> fix: don't panic on `pnpm` lockfiles with an invalid path

pkg/semantic/version-maven.go, pkg/semantic/version-packagist.go, pkg/semantic/version-pypi.go, pkg/semantic/version-semver.go
This will later be enforced by `revive`
=> refactor: rename variables to avoid shadowing builtin functions

.github/workflows/checks.yml, .github/workflows/release.yml, .golangci.yaml, Makefile
This will make it easier to discover new linters and upgrade to v2
=> chore: update `golangci-lint` to latest v1 version and simplify config

.golangci.yaml, pkg/semantic/version-debian.go, pkg/semantic/version-maven.go, pkg/semantic/version-packagist.go, pkg/semantic/version-pypi.go, pkg/semantic/version-rubygems.go, pkg/semantic/version-semver.go, pkg/semantic/version.go
=> refactor: use `range` for looping over ints

.golangci.yaml, pkg/database/api_test.go
Neither of these have violations, though for some reason enabling `govet` makes `staticcheck` flag an area of code in a test that could be nil as apparently it doesn't understand that we're using `t.Fatal`?
Sticking a `return` makes it happy, so I'm doing that for now and will revisit when we're upgraded to v2 of the linter
=> chore: enable `predeclared` and `govet` linters

pkg/semantic/parse_test.go
We no longer need to add `CRAN` manually as it's supported by `lockfile`, but we should be adding `Debian` and `Red Hat` as they are not
=> test(semantic): address todo relating to `CRAN` ecosystem

.goreleaser.yml
For some reason it never clicked to me that as this is an array, we can spread items across multiple lines/items
=> chore: split `ldflags` over multiple items

go.mod, internal/reporter/reporter_test.go, main.go
This lets us use `osv-scalibr` - it has meant `govet` now complains when using formatting functions without a constant format string, which I've just addressed by adding such a string rather than adding two new dedicated functions for not-formatting
=> feat: update to Go v1.24

pkg/database/api-check_test.go, pkg/database/api_test.go, pkg/database/dir_test.go, pkg/database/zip_test.go
For most if not all of these getting an unexpected error will mean the other value is `nil` resulting in a confusing pointer dereference error
=> test: use `t.Fatalf` for unexpected errors

renovate.json
This is based on the configuration we're using in `osv-scanner` which has `osv-scalibr` updated in its own pull request
=> ci: have `osv-scalibr` updates be done in a dedicated pull request
