.github/workflows/checks.yml

ci: setup checks

---

.golangci.yaml
detector/database/cache.go
detector/database/load.go
detector/parsers/parse-composer-lock.go
detector/parsers/parse-gemfile-lock.go
detector/parsers/parse-npm-lock.go
detector/parsers/parse-requirements-txt.go

Fixes most of what's being reported by `make lint` - the remaining ones I'll look at later.

chore: linting fixes

---

detector/parsers/helpers_test.go
detector/parsers/parse-composer-lock.go
detector/parsers/parse-composer-lock_test.go
detector/parsers/parse-gemfile-lock_test.go
detector/parsers/parse-npm-lock-v1_test.go
detector/parsers/parse-npm-lock-v2_test.go
detector/parsers/parse-npm-lock.go
detector/parsers/parse-requirements-txt.go
detector/parsers/parse-requirements-txt_test.go

By which I mean, actually take it into account 😂

fix: improve "file not found" handling

---

README.md

I'm wanting to add at least a  `--list-db-stats` command too at some point.

docs: document auxiliary commands

---

CONTRIBUTING.md

I based it off a few things, but completely custom written 😄

docs: add contributing documentation

---

.github/workflows/codeql-analysis.yml

Hopefully this won't flag anything 🤣

ci: setup codeql analysis

---

.golangci.yaml
Makefile

Should make it a littler easier

build: add command for formatting with prettier

---

LICENSE

"I'm sure this won't come back to bite me"

fix: add a license

---

CONTRIBUTING.md
detector/database/cache.go
detector/parsers/parsers.go
main.go

Me learning more about how to nicely do errors in Go 😅

fix: improve how errors are outputted a little

---

.github/workflows/codeql-analysis.yml
.goreleaser.yml

ci: fix release config

---

.github/workflows/checks.yml
.github/workflows/release.yml
CONTRIBUTING.md

ci: setup linting

---

.golangci.yaml
Makefile
main.go

It seems to work fine, though locally `date` didn't seem to be getting set for snapshots but we'll see what happens 🤷 
Resolves #41

feat: support `--version` flag

---

.github/workflows/checks.yml
.prettierignore
.prettierrc.json
CONTRIBUTING.md

It's unlikely things will move around again, but I'm sick of not having updated `.prettierignore` and having the pnpm fixtures be formatted 🙈

ci: run prettier

---

main.go

This should make things better for the long-run, since `os.Exit` calls are not testable and similarly affect other tools like profiling (since `defer`'d functions don't get called) and [`go-cmdtest`](https://github.com/google/go-cmdtest) which I want to look into using.
This is pretty straight forward _except_ for handling errors when loading databases - for now I've written a bit of a kludge which I aim to cleanup when I tackle error handling / outputting in general. (I'm also expecting to break this up into a `cli` or `commands` package at some point, I'm just waiting for things to stabilize a bit more)

refactor: use `run` function that returns an error code to avoid multiple `os.Exit` calls

---

README.md
internal/lockfile/parse.go
internal/lockfile/parse_test.go
main.go

feat: support being passed a directory to check for lockfiles

---

internal/reporter/report.go
internal/reporter/report_test.go
main.go

If anyone can come up with a better name to `Form`, I'd be interested in hearing it 😅

fix: handle plural & singular form properly

---

main.go

Currently they're a bit out of date and don't make much sense

fix: update flag usage text to be more accurate

---

README.md
pkg/lockfile/fixtures/npm/commits.v1.json
pkg/lockfile/fixtures/npm/commits.v2.json
pkg/lockfile/parse-npm-lock-v1_test.go
pkg/lockfile/parse-npm-lock-v2_test.go
pkg/lockfile/parse-npm-lock.go
pkg/lockfile/parse-yarn-lock.go

feat: support parsing commits from `package-lock.json` files

---

README.md
pkg/lockfile/fixtures/pnpm/commits.yaml
pkg/lockfile/parse-pnpm-lock.go
pkg/lockfile/parse-pnpm-lock_test.go

feat: support parsing commits from `pnpm.yaml` files

---

README.md

This shouldn't be nested under the "Offline" header

docs: adjust header level

---

pkg/database/zip.go

I came across this while working more on #114 - it _feels_ like a performance improvement (before it would take at least ~10s to load 170984 OSVs from the GH database, now it takes ~6s), but attempting to benchmark it seemed to indicate it either wasn't or actually made performance worse (though memory use did seem to drop slightly as I'd expect)
However I'm going to land it because the underlying logic makes sense (and is flagged by my IDE): `defer` in a loop gets called when the function ends, not at the end of a loop iteration so we're holding on to these files longer than we need which adds up when you're working with a sizable database like the GitHub Advisory DB - by moving the core of loop logic into a function, `defer` will happen within the loop.
This is a best practice, so I …

perf: close each osv file immediately after being loaded instead of after all loading is finished

---

internal/configer/load.go
main.go
main_test.go

This makes things a bit more consistent, which is nice.

fix: clean lockfile and config paths so that output is consistent

---

README.md

Just a bit of a rewrite following on from #130.

docs: improve readme section about csv parsers

---

main_test.go

I noticed a very minor inconsistency with a few of the tests, and decided to just wrap it all up into a single function

test: simplify core cli cases a bit

---

README.md
main.go

feat: remove `--cache-all-databases` flag

---

main.go
pkg/database/dir.go
pkg/database/mem-check.go
pkg/database/osv.go
pkg/database/zip.go
pkg/semantic/version.go

I thought I was already doing this but apparently I missed a couple 🤷

refactor: make method receivers consistent

---

README.md
main_test.go
pkg/lockfile/ecosystems_test.go
pkg/lockfile/fixtures/poetry/empty.lock
pkg/lockfile/fixtures/poetry/not-toml.txt
pkg/lockfile/fixtures/poetry/one-package-with-metadata.lock
pkg/lockfile/fixtures/poetry/one-package.lock
pkg/lockfile/fixtures/poetry/source-git.lock
pkg/lockfile/fixtures/poetry/source-legacy.lock
pkg/lockfile/fixtures/poetry/two-packages.lock
pkg/lockfile/parse-poetry-lock.go
pkg/lockfile/parse-poetry-lock_test.go
pkg/lockfile/parse.go
pkg/lockfile/parse_test.go

feat: support parsing `poetry.lock`

---

README.md
internal/reporter/reporter_test.go
main_test.go
pkg/lockfile/ecosystems.go
pkg/lockfile/fixtures/nuget/empty.v0.json
pkg/lockfile/fixtures/nuget/empty.v1.json
pkg/lockfile/fixtures/nuget/not-json.txt
pkg/lockfile/fixtures/nuget/one-framework-one-package.v1.json
pkg/lockfile/fixtures/nuget/one-framework-two-packages.v1.json
pkg/lockfile/fixtures/nuget/two-frameworks-different-packages.v1.json
pkg/lockfile/fixtures/nuget/two-frameworks-duplicate-packages.v1.json
pkg/lockfile/fixtures/nuget/two-frameworks-mixed-packages.v1.json
pkg/lockfile/parse-nuget-lock-v1_test.go
pkg/lockfile/parse-nuget-lock.go
pkg/lockfile/parse-nuget-lock_test.go
pkg/lockfile/parse.go
pkg/lockfile/parse_test.go

Port of https://github.com/google/osv-scanner/pull/98

feat: support parsing NuGet `packages.lock.json` lockfiles

---

generators/GenerateMavenVersions.java
generators/generate-debian-versions.py
generators/generate-packagist-versions.php
generators/generate-pypi-versions.py
generators/generate-rubygems-versions.rb

This is some minor fixes and improvements to the generators, which I'm just landing ahead of setting up a workflow that will run them regularly (so these changes have all been tested).

chore: improve generators

---

generators/GenerateMavenVersions.java
generators/generate-debian-versions.py
generators/generate-packagist-versions.php
generators/generate-pypi-versions.py
generators/generate-rubygems-versions.rb

This is really all because of Maven, whose version comparison implementation is apparently pretty buggy - for now I'm going to ignore it and hope that in ~6 months when I check back on things at least some of the bugs will be fixed.

chore: support skipping known unsupported comparisons in generators

---

pkg/lockfile/parse-requirements-txt.go

refactor: use `strings.Cut`

---

fixtures/locks-e2e/1-Gemfile.lock.out.txt
fixtures/locks-e2e/1-Pipfile.lock.out.txt
fixtures/locks-e2e/1-poetry.lock.out.txt
fixtures/locks-e2e/1-yarn.lock.out.txt
fixtures/locks-e2e/2-go.mod.out.txt
fixtures/locks-e2e/2-package-lock.json.out.txt
fixtures/locks-e2e/2-poetry.lock.out.txt
fixtures/locks-e2e/2-pom.xml.out.txt
fixtures/locks-e2e/2-yarn.lock.out.txt
fixtures/locks-e2e/3-yarn.lock.out.txt

This will probably be the last time as they're too noisy

test: update e2e fixtures

---

generators/generate-rubygems-versions.rb

This is all pretty harmless but there's some nice small improvements in here

refactor: apply rubocop suggestions to Ruby generator

---

main_test.go

I'd technically class this as a bug but don't think it'll be considered important for anyone to actually action so I'm just going to update the fixture 🤷

test: update fixture

---

pkg/lockfile/fixtures/pnpm/commits.v9.yaml
pkg/lockfile/fixtures/pnpm/mixed-groups.v53.yaml
pkg/lockfile/fixtures/pnpm/mixed-groups.v54.yaml
pkg/lockfile/fixtures/pnpm/mixed-groups.v6.yaml
pkg/lockfile/fixtures/pnpm/mixed-groups.v9.yaml
pkg/lockfile/fixtures/pnpm/multiple-versions.v9.yaml
pkg/lockfile/fixtures/pnpm/no-packages.v9.yaml
pkg/lockfile/fixtures/pnpm/one-package-dev.v9.yaml
pkg/lockfile/fixtures/pnpm/one-package.v9.yaml
pkg/lockfile/fixtures/pnpm/peer-dependencies-advanced.v9.yaml
pkg/lockfile/fixtures/pnpm/peer-dependencies.v9.yaml
pkg/lockfile/fixtures/pnpm/scoped-packages.v9.yaml
pkg/lockfile/parse-pnpm-lock-v9_test.go
pkg/lockfile/parse-pnpm-lock.go

Cherry-picked from google/osv-scanner#934

feat: support PNPM v9 lockfiles

---

.github/workflows/scorecard.yml
README.md

ci: setup scorecard

---

.github/workflows/checks.yml
.github/workflows/release.yml
.github/workflows/semantic.yml

ci: pin dependencies

---

.github/workflows/release.yml

ci: update linter version in release workflow

---

main_test.go

New `guzzlehttp/psr7` vulnerability has dropped 😅

test: update fixtures

---

.github/workflows/checks.yml
.github/workflows/release.yml

I don't know why I didn't do this originally, since I've used `matrix` a lot before 🤷

ci: use matrix for running tests across different OSs

---

.golangci.yaml
internal/configer/update_test.go
internal/reporter/report_test.go
internal/reporter/reporter_test.go
main_test.go
pkg/database/api_test.go
pkg/database/osv_test.go
pkg/database/vulnerabilities_test.go
pkg/lockfile/csv_test.go
pkg/lockfile/parse-maven-lock_test.go
pkg/lockfile/parse_test.go
pkg/semantic/compare_test.go

test: remove unneeded loop copies

---

pkg/semantic/parse.go
pkg/semantic/parse_test.go

feat: support comparing Ubuntu versions
